### ISSUE TITLE
GUID Error

### ISSUE THREAD

**Issue by CorniiDog** [primus852/stock-news#3]
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\envs\stonks\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
>     return self._engine.get_loc(casted_key)
>   File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas\_libs\hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas\_libs\hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'guid'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "newsgathering.py", line 239, in <module>
>     df = sn.read_rss()
>   File "C:\ProgramData\Anaconda3\envs\stonks\lib\site-packages\stocknews\__init__.py", line 124, in read_rss
>     guid = df.loc[df['guid'] == entry.guid]
>   File "C:\ProgramData\Anaconda3\envs\stonks\lib\site-packages\pandas\core\frame.py", line 3024, in __getitem__
>     indexer = self.columns.get_loc(key)
>   File "C:\ProgramData\Anaconda3\envs\stonks\lib\site-packages\pandas\core\indexes\base.py", line 3082, in get_loc
>     raise KeyError(key) from err
> KeyError: 'guid'

Not to mention, I checked the trading API URL and it's stated to be deprecated: https://api.worldtradingdata.com/api/v1/history

**Comment by CorniiDog** [comment]
Found the problem. There may be a chance that the CSV file destination may end up corrupted. Just delete the CSV file and rerun the program.
